### ISSUE TITLE
collaboration?

### ISSUE THREAD

**Issue by pierreozoux** [MarvAmBass/docker-piwik#17]
Hi!

Would you like to collaborate on this: https://github.com/piwik/docker-piwik/issues/1

Then we could share the work to maintain upstream image. And you could then base this image on the official one?

What do you think?

Best!

Pierre

**Comment by MarvAmBass** [comment]
Hi Pierre,

you're talking about the official piwik container right? Would be cool if it's the official one.

what kind of collaboration? If you want to make it autoconfigurable via ENV Variables etc. I would love to help - with official developers on the other side this would be much more stable and official than my reverse engineered approach.

Well I've to thing about this one, because I try to maintain production ready, secure and super stable containers. Switching the base image would be a huge break (since I also maintain the super secured nginx image which is currently the base of this container)

I'd only consider this after a deeper look on your base image, image and webserver configuration, if it's to easy to be in some kind of unsecure/debug mode without noticing, I'd rather stick with my own images.

Thanks and Kind regarts

Marvin

**Comment by pierreozoux** [comment]
There is one main difference, it is one container per service. So php is separated from nginx (which is more secure in my opinion.)

I think your hack is still needed, so the idea would be to let the official image vanilla, and you could add your hack on top (I like your hack :) )

But it is up to you :) (I know it is quiet some work :/ )

**Comment by MarvAmBass** [comment]
I think about it, at least the container seperation seems much cleaner and interesting!

thx

**Comment by mattab** [comment]
Hi @MarvAmBass

Great to see @pierreozoux asking you to collaborate :-) We would love to work together to make our Docker Piwik Container the most useful, maintained, and mark it as "Official" for the community to enjoy  :+1:  :rocket:

**Comment by MarvAmBass** [comment]
due to other timeconsuming projects I've to decline

I'm sorry
